### ISSUE TITLE
Actor Can Target Dead Actors

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp3#27]
**Describe the bug**
Actor can target and attack dead actors. Dead Actors can receive more damage. 

**To Reproduce**
1. Limit to 1 actor per troupe
2. start combat
3. wait for actor to die

**Expected behavior**
Dead Actor is ignored as a target and doesnt respond to new damage. 

**Screenshots**
![image](https://github.com/Snayff/nqp3/assets/23128268/0c20e2b2-6f1d-40b6-bb30-45f3a2f3ac75)

**Additional context**
Suggests `is_targetable` is either not being set or is being ignored.

**Comment by eh-jogos** [comment]
I think this was fixed somewhere along the way, but I think `is_targetable` is still not being set. Or rather, it is being set to `false`  in the function `_on_health_depleted()` but it is not being read anywhere else:
![image](https://github.com/Snayff/nqp3/assets/13070158/49a83974-8c6b-4ac7-b595-0dd35edba093)

The way this got "accidentaly" fixed was that at some point I added this function to validate targets in **actor_ai.gd** which checks if the target is alive:

https://github.com/Snayff/nqp3/blob/6cc536758856a2d3c776c728d953f1d4243201b9/scripts/components/actor_ai.gd#L99C1-L102

Is there any other use cases for `is_targetable`? Or do you want me to change the check to use `is_targetable` rather than checking if the enemy is alive?

**Comment by snayff** [comment]
I think we should probably scrap `is_targetable` and check for the actual parameters we want  such as not being dead.
